sonar.projectKey = Graziela2705_RepositoryXPTO 
sonar.organization = graziela2705


# Este é o nome e a versão exibidos na interface do usuário do SonarCloud. 
#sonar.projectName=RepositoryXPTO 
#sonar.projectVersion=1.0


# O caminho é relativo ao arquivo sonar-project.properties. Substitua "\" por "/" no Windows. 
#sonar.sources=. 

# Codificação do código-fonte. O padrão é a codificação padrão do sistema. 
#sonar.sourceEncoding=UTF-8