name: Primeiro pipeline

on: 
   push:
      branches: [main]

jobs:
   teste:
      runs-on: ubuntu-latest

      steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar C#
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Instalar Dependências
        run: pip install pytest

      - name: Execução de Testes
        run: pytest
        

   deploy:
      needs: teste
      runs-on: ubuntu-latest
      steps:
      - run: echo "Deploy realizado com sucesso!"

        
                