name: Segunda pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Restaurar Dependências
        run: dotnet restore "Test_C#/Test_C#.csproj"

      - name: Compilar Projeto
        run: dotnet build "Test_C#/Test_C#.csproj" --no-restore

      - name: Executar Testes
        run: dotnet test "Test_C#/Test_C#.csproj" --no-build --logger "console;verbosity=minimal"

  deploy:
    needs: testes
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: echo "Deploy realizado com sucesso!"